### ISSUE TITLE
If you set a CDN using config.action_controller.asset_host, precompile fails with NoMethodError: undefined method `protocol' for nil:NilClass

### ISSUE THREAD

**Issue by jasonfb** [richpeck/exception_handler#102]
symptom: in my Rails 6.1.3.1 app

in production.rb

when I set
```
  config.action_controller.asset_host = "d2qo3ls92ks92kw.cloudfront.net"
```

and have this gem installed

```
gem 'exception_handler'
```

asset precompile fails with this error

```
** Execute assets:precompile
rails aborted!
NoMethodError: undefined method `protocol' for nil:NilClass
/Users/jason/.rvm/gems/ruby-2.6.6/gems/actionview-6.1.3.2/lib/action_view/helpers/asset_url_helper.rb:303:in `compute_asset_host'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/actionview-6.1.3.2/lib/action_view/helpers/asset_url_helper.rb:212:in `asset_path'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/actionview-6.1.3.2/lib/action_view/helpers/asset_url_helper.rb:231:in `asset_url'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/exception_handler-0.8.0.1/app/assets/stylesheets/styles/_exception.css.erb:28:in `_evaluate_template'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/erb_processor.rb:26:in `call'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/erb_processor.rb:13:in `call'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:23:in `block in call'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/utils.rb:200:in `dfs'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:24:in `call'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:134:in `block in find'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `each'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `find'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-rails-3.2.2/lib/sprockets/rails/task.rb:67:in `block (3 levels) in define'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/sprockets-rails-3.2.2/lib/sprockets/rails/task.rb:66:in `block (2 levels) in define'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/jason/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/railties-6.1.3.2/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/railties-6.1.3.2/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/rake-13.0.3/lib/rake/rake_module.rb:59:in `with_application'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/railties-6.1.3.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/railties-6.1.3.2/lib/rails/command.rb:52:in `invoke'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/railties-6.1.3.2/lib/rails/commands.rb:18:in `<main>'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/jason/Work/Verso_Commerce/verso2/bin/rails:5:in `<top (required)>'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/Users/jason/.rvm/gems/ruby-2.6.6/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
/Users/jason/Work/Verso_Commerce/verso2/bin/spring:10:in `require'
/Users/jason/Work/Verso_Commerce/verso2/bin/spring:10:in `block in <top (required)>'
/Users/jason/Work/Verso_Commerce/verso2/bin/spring:7:in `tap'
/Users/jason/Work/Verso_Commerce/verso2/bin/spring:7:in `<top (required)>'
bin/rails:2:in `load'
bin/rails:2:in `<main>'
Tasks: TOP => assets:precompile

```

posted to stackoverflow here https://stackoverflow.com/questions/67494836/rails-6-1-nomethoderror-undefined-method-protocol-for-nilnilclass-when-setti

**Comment by savanr** [comment]
This is because of the not specified protocol for the asset_host value.

`config.action_controller.asset_host = "https://#{Rails.application.credentials.dig(:cdn_asset_host)}"`

Move CDN value to the credentials.yml for security purposes and load as mentioned above.

**Comment by jasonfb** [comment]
https://stackoverflow.com/questions/67494836/rails-6-1-nomethoderror-undefined-method-protocol-for-nilnilclass-when-setti
2022-01-11 -- update: the asset_host setting should have the protocol (https) with **https://**

the problem should be fixed if you add the protocol correctly
