### ISSUE TITLE
rails db:migrate running into issues with errors table

### ISSUE THREAD

**Issue by drkaleem** [richpeck/exception_handler#108]
after upgrading to 0.8.0.2 running into this issue. Please help 

```
rails db:migrate
/home/jdeinteg/.rvm/gems/ruby-3.0.0/gems/exception_handler-0.8.0.2/lib/exception_handler/config.rb:143:in `initialize': Migration Required → "errors" doesn't exist (ExceptionHandler::Error)
        from /home/jdeinteg/.rvm/gems/ruby-3.0.0/gems/exception_handler-0.8.0.2/lib/exception_handler/engine.rb:45:in `new'
jdeinteg@JDEDMZBETA:~/sites/hitt_jdedmz$        from /home/jdeinteg/.rvm/gems/ruby-3.0.0/gems/exception_handler-0.8.0.2/lib/exception_handler/engine.rb:45:in `block in <class:Engine>'
        from /home/jdeinteg/.rvm/gems/ruby-3.0.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:32:in `instance_exec'
        from /home/jdeinteg/.rvm/gems/ruby-3.0.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:32:in `run'
        from /home/jdeinteg/.rvm/gems/ruby-3.0.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:61:in `block in run_initializers'
```

**Comment by code-andres** [comment]
To anyone with this problem use `rake db:migrate`.

In the file exception_handler-0.8.0.2/lib/exception_handler/config.rb:143 there is a validation for the passeds ARGV and validates the use of `rake`, instead of rails.
