### ISSUE TITLE
Possible Unicorn issue?

### ISSUE THREAD

**Issue by bytenel** [richpeck/exception_handler#14]
I have a unicorn server running exception_handler. It works fine in development but when I push to staging I get a bad gateway error. Upon inspecting the unicorn.log file I see that the problem is a NoMethodError generated by the exception handler gem. Not sure what's up honestly.
```
E, [2015-04-07T07:41:09.893741 #3482] ERROR -- : undefined method `setup' for ExceptionHandler:Module (NoMethodError)
/home/deployer/apps/taxalli/releases/20150407113904/config/initializers/exception_handler.rb:6:in `<top (required)>'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:241:in `load'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:241:in `block in load'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:241:in `load'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/railties-4.1.0/lib/rails/engine.rb:648:in `block in load_config_initializer'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/activesupport-4.1.0/lib/active_support/notifications.rb:161:in `instrument'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/railties-4.1.0/lib/rails/engine.rb:647:in `load_config_initializer'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/railties-4.1.0/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/railties-4.1.0/lib/rails/engine.rb:611:in `each'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/railties-4.1.0/lib/rails/engine.rb:611:in `block in <class:Engine>'
/usr/local/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
/usr/local/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/2.0.0/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
/usr/local/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.0.0/tsort.rb:209:in `block in each_strongly_connected_component_from'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/railties-4.1.0/lib/rails/initializable.rb:44:in `each'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/railties-4.1.0/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/lib/ruby/2.0.0/tsort.rb:203:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/2.0.0/tsort.rb:180:in `each'
/usr/local/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
/usr/local/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/railties-4.1.0/lib/rails/initializable.rb:54:in `run_initializers'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/railties-4.1.0/lib/rails/application.rb:288:in `initialize!'
/home/deployer/apps/taxalli/releases/20150407113904/config/environment.rb:5:in `<top (required)>'
config.ru:4:in `require'
config.ru:4:in `block in <main>'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
config.ru:1:in `new'
config.ru:1:in `<main>'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/unicorn-4.7.0/lib/unicorn.rb:48:in `eval'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/unicorn-4.7.0/lib/unicorn.rb:48:in `block in builder'

/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/unicorn-4.7.0/lib/unicorn.rb:48:in `block in builder'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/unicorn-4.7.0/lib/unicorn/http_server.rb:750:in `call'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/unicorn-4.7.0/lib/unicorn/http_server.rb:750:in `build_app!'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/unicorn-4.7.0/lib/unicorn/http_server.rb:623:in `init_worker_process'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/unicorn-4.7.0/lib/unicorn/http_server.rb:643:in `worker_loop'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/unicorn-4.7.0/lib/unicorn/http_server.rb:527:in `spawn_missing_workers'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/unicorn-4.7.0/lib/unicorn/http_server.rb:538:in `maintain_worker_count'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/unicorn-4.7.0/lib/unicorn/http_server.rb:303:in `join'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/gems/unicorn-4.7.0/bin/unicorn:126:in `<top (required)>'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/bin/unicorn:23:in `load'
/home/deployer/apps/taxalli/shared/bundle/ruby/2.0.0/bin/unicorn:23:in `<main>'                                               
```

**Comment by richpeck** [comment]
Hmm wow okay.

Give me some time and I'll get back to you. If it's working in dev, it might be unicorn but I'll have a deeper look in a second. Just doing some monkey patching

**Comment by bytenel** [comment]
Sounds good, yea it seemed to work in dev but crashed my server in staging / prod. I had to rip it out of this project but I'd love to help get this fixed so I can use it in future projects.

**Comment by richpeck** [comment]
Okay looks like the first line gives us the reported error:

` undefined method `setup'` for the `initializer`.


The `setup` method is as follows:

`def self.setup
	yield(config) if block_given?
end`

---

My first step would be to comment out the initializer.

If this works, the problem is with the way the initializer is connecting to the gem etc, which could be a unicorn issue if it's trying to cache the app beforehand.

Another issue you may have might be to do with the development / production situation. Since you're deploying to production, have you got any other specifics in place which might be preventing the gem's files from loading? Are you sure you ran `bundle install` on the server? Lots of little problems which may seem trivial, but actually end up being the main problem.

--

My Skype is "gorkite" if you'd like to talk about it further

**Comment by bytenel** [comment]
Cool I'll take a look and setup another instance of a server with a similar Unicorn/NGinx setup when I get some free time. Thanks for taking a look!

**Comment by richpeck** [comment]
No problem - let me know if it resolves. I want to get a new version released, and this would be a great fix to make
