### ISSUE TITLE
How do you see the Exception View in dev?

### ISSUE THREAD

**Issue by wmantegna** [richpeck/exception_handler#31]
I haven't figured out how to see the Exception View in dev. When I'm in production (on Heroku) and an error occurs, the error pages appear just fine, but I would like to customize this page, which is much harder if I can't see it in my dev environment.

**Comment by richpeck** [comment]
Hi Bill! 

Thanks for using the gem.

Since the latest version (`0.5.1`), we've included a handy "dev" config option, which can be set as follows: 

![image](https://cloud.githubusercontent.com/assets/1104431/14585447/ebaeebc0-046d-11e6-9cdd-6d9688b58500.png)

This overrides the `consider all requests local` option, allowing the gem to load in development as it does in production.

If you try the above, it should work for you

Rich

**Comment by wmantegna** [comment]
I'm throwing the following error in the controller for my root path: `raise Exception.new('ouch')`

I've tried changing the dev attribute, but it hasn't been making a difference in output. However, if I change `config.consider_all_requests_local = true` to false in _development.rb_, then I see the following (the output of which doesn't change when I change _exception_handler/exception/show.html.erb_ view):

```
500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.
```

**Comment by richpeck** [comment]
Hi Bill,

That's because you're sending a custom exception. I have a feature lined up to handle these, but at the moment it only handles `40x` & `50x` errors. 

Do you want me to release the updated version to fix this issue or is it non-essential?

Thanks again!

Rich

**Comment by wmantegna** [comment]
I just tried raising the following errors (1 at a time), and am still seeing the same page:
```
render :status => :forbidden, :text => "Forbidden fruit"
raise "error"
```
I'm seeing the message "forbidden fruit" which seems good, but I'm not seeing the boilerplate in _exception_handler/exception/show.html.erb_.

Is there a specific way to raise a 40x or 50x error that triggers exception_handler in the current release that I can test in a dev environment?

If not, and if the updated version is stable enough, I would love it if you could release it. Being able to test in dev is important to my development methodologies.

**Comment by defec8edc0de** [comment]
Hello richpeck,
thanks for your work.

I have as well a problem testing the exception_handler exceptions in development environment...
My environment:
- ruby 2.2.3p173
- rails (4.2.5)
- exception_handler (0.5.1)

The steps I took to install exception_handler:

1.  Add to Gemfile: `gem 'exception_handler', '~> 0.5.0'`
2.  Run: `bundle`
3.  Run: `rails generate exception_handler:views -v views controllers`
4.  Put the following in my `config/application.rb`
```
      config.exception_handler = {
        dev:    true,
        db:     false, #-> defaults to :errors if true, else use :table_name
        email:  false, #-> need to integrate
        social: {
            :twitter    =>      'frontlineutils',
            :facebook   =>      'frontline.utilities',
            :linkedin   =>      'frontline-utilities',
            :youtube    =>      'frontlineutils',
            :fusion     =>      'frontlineutils',
            :url => {
                    :facebook   =>      'https://facebook.com',
                    :twitter    =>      'http://twitter.com',
                    :youtube    =>      'https://youtube.com/user',
                    :linkedin   =>      'https://linkedin.com/company',
                    :fusion     =>      'https://frontlinefusion.com',
                },
        },
        layouts: {
            '400' => nil,
            '404' => nil,
            '500' => 'exception'
       }
    }
```

I use the following command to start the server:
  `rvmsudo rails server -p 80 -b 0.0.0.0 -e development`
When I produce a 500 exception or visit a non-existent route, it gives me the normal rails exception pages...
If I start the server with `rails server` (should be port 3000, localhost only, development), it seems to work and produces the plain error page described by wmantegna when trying to open a non-existent route:

> 500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.

Additionally I get the following error in the log:


```
ActionController::RoutingError (No route matches [GET] "/api/papy"):
  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'

  ...

Processing by ExceptionHandler::ExceptionController#show as HTML
  Rendered exception_handler/exception/show.html.erb within layouts/application (52.1ms)
Completed 500 Internal Server Error in 97ms (ActiveRecord: 0.0ms)
Error during failsafe response: undefined local variable or method `details' for #<#<Class:0x000000040be6f0>:0x000000037653d8>
  /home/sfunke/android-privacy-api-servers/papi-backend/papi-backend/app/views/exception_handler/exception/show.html.erb:29:in `_app_views_exception_handler_exception_show_html_erb___26827800028745539
3_31494000'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionview-4.2.5/lib/action_view/template.rb:145:in `block in render'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.5/lib/active_support/notifications.rb:166:in `instrument'

...
```

**Comment by richpeck** [comment]
Thanks for the message, much appreciated. 

Two things:

1. Where in the stack are you creating the error? Middleware / Controller / View?
2. Can you show me a screenshot of your error page & console?

Thanks again, I'm working on this now so should be able to respond quite quickly

Rich

**Comment by defec8edc0de** [comment]
I updated my question and included the full stacktrace, so you can see where the error gets created, thank you for the fast reply!

**Comment by richpeck** [comment]
#Error 
Okay thanks for the update - I think I can see the problem:

```
Error during failsafe response: undefined local variable or method `details' for #<#<Class:0x000000040be6f0>:0x000000037653d8>
  /home/sfunke/android-privacy-api-servers/papi-backend/papi-backend/app/views/exception_handler/exception/show.html.erb:29:in `_app_views_exception_handler_exception_show_html_erb___2682780002874553
```

This is the *second* error that's raised. The first is the `404` error `(No route matches [GET] "/api/papy")`

What happens is the 404 error is picked up by `ExceptionHandler`, it will then work on invoking the various views etc to make it work. The issue is that the `exception_handler` view is unable to access the `details` method / var, which is dotted throughout the [view](https://github.com/richpeck/exception_handler/blob/master/app/views/exception_handler/exception/show.html.erb#L7):

`#{details[:name]}`

The result is that `exception_handler` cannot process the 500 error and so the Rails standard 500 exception is raised. This is why you're seeing the bland page.

----

#Fix 

The fix is to make sure that `ExceptionHandler` has access to the `details` method in the view.

I see that you've generated the views etc in your application yourself. If you give me access to your repo, I'll go and see what the issue is.

Specifically, the `details` method is part of the [`ExceptionHandler` helper](https://github.com/richpeck/exception_handler/blob/master/app/helpers/exception_handler/application_helper.rb#L19). If you've generated your own controller, perhaps this is not being loaded; something I can only consider if I see your code.

--

Ultimately, `ExceptipnHandler` *is* working, it's just you have a small issue causing it to fail

**Comment by defec8edc0de** [comment]
Okay thanks rich, that was a very informative and detailed explanation.

Short update to my actual problem and my fix:

So the problem was, that I updated from exception_handler `0.4.7 to 0.5.1` with 
`bundle update exception_handler`
During the process the **app/controller/exception_handler/application_controller.rb** got not updated, hence the `details `method was missing.
After copying it from your repository, it worked nicely, but for the route-missing-exception it took the default application layout. I changed it in the exception_handler config for 400 and 404 to the `'exception'` layout...
Then the `root_url` from the url_helper was missing in the `routes.rb` ...
(this is in rails 4+ by default not set apparently, but would resolve to  `root 'rails/welcome#index'` in the Welcome Aboard page)
Anyway, after I added a root route in routes.rb it worked like a charm.
Thanks for the fast help!

**Comment by richpeck** [comment]
For the routes, one of the problems with Rails engine isolated namespaces is the inaccessibility of the main app routes in the engine. This means that if you use `application` layout with `ExceptionHandler` (EH being an engine), any "main" routes in your layout need the `main_app.***_path` prefix.

http://edgeapi.rubyonrails.org/classes/Rails/Engine.html#class-Rails::Engine-label-Using+Engine-27s+routes+outside+Engine

This seems to have a VERY good solution, which I think I'll implement in the next verison: http://stackoverflow.com/a/27018875/1143732

**Comment by defec8edc0de** [comment]
Hi Rich,
you wrote earlier in this issue regarding custom exceptions:

> "I have a feature lined up to handle these, but at the moment it only handles 40x & 50x errors."

I try to use `exception_handler` now with a custom exception I declared in my main app under `app/exceptions/papi_exception.rb`:

```
  class PapiException < StandardError
    attr_reader :code
    
    def initialize(code)
      @code = code
    end
    
    def to_s
      "[#{code}] #{super}"
    end
  end  
```

In the `app/controller/exception_handler/exception_controller.rb` I changed `show` as following:

```
    def show
        @exception = ExceptionHandler::Exception.new request
        if (json_or_api_request?)
          if (@exception.exception.is_a?(PapiException))
            render json: @exception.exception.message, status: @exception.exception.code
          else
            render json: @exception.message, status: @exception.status
          end
        else
          render status: @exception.status
        end
    end
```

I raise the custom exception like this:
`raise PapiException.new(401), "You are not authorized! Provide a valid X-PAPI-API-KEY HTTP Header to use this resource!"`
When I raise this exception from within one of my Engine modules code, or when I provoke a RouteNotFound exception in the main app everything works fine and expected....but when I raise the same exception in my main apps `app/controller/application_controller.rb` in an API authorization method, I get again the plain 500 fallback error page from rails:

```
500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.
```
Unfortunately I can't provide you access to the repository, because it is private...maybe the stacktrace to this error can help you to figure out the problem?

```
=> Booting WEBrick
=> Rails 4.2.6 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2016-06-14 22:04:53] INFO  WEBrick 1.3.1
[2016-06-14 22:04:53] INFO  ruby 2.2.3 (2015-08-18) [x86_64-linux]
[2016-06-14 22:04:53] INFO  WEBrick::HTTPServer#start: pid=30791 port=3000


Started GET "/api/pets/" for 192.168.200.1 at 2016-06-14 22:05:13 +0200
  ActiveRecord::SchemaMigration Load (0.1ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by Api::PetsController#index as HTML
Completed 500 Internal Server Error in 15ms (ActiveRecord: 0.0ms)

PapiException ([401] You are not authorized! Provide a valid X-PAPI-API-KEY HTTP Header to use this resource!):
  app/controllers/application_controller.rb:55:in `check_api_authorization'



PapiException: [401] You are not authorized! Provide a valid X-PAPI-API-KEY HTTP Header to use this resource!
	from /home/sfunke/android-privacy-api-servers/papi-backend/papi-backend/app/controllers/application_controller.rb:55:in `check_api_authorization'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:432:in `block in make_lambda'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:164:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:164:in `block in halting'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `block in call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `each'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `block in instrument'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `instrument'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activerecord-4.2.6/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/abstract_controller/base.rb:137:in `process'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionview-4.2.6/lib/action_view/rendering.rb:30:in `process'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_controller/metal.rb:196:in `dispatch'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_controller/metal.rb:237:in `block in action'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:74:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:43:in `serve'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:43:in `block in serve'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in `each'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in `serve'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:817:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/middleware/flash.rb:260:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/middleware/cookies.rb:560:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activerecord-4.2.6/lib/active_record/query_cache.rb:36:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activerecord-4.2.6/lib/active_record/migration.rb:377:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/middleware/reloader.rb:73:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/web-console-2.3.0/lib/web_console/middleware.rb:28:in `block in call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `catch'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/railties-4.2.6/lib/rails/rack/logger.rb:38:in `call_app'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `block in call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `block in tagged'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:26:in `tagged'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `tagged'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/middleware/static.rb:120:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/railties-4.2.6/lib/rails/engine.rb:518:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/railties-4.2.6/lib/rails/application.rb:165:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
	from /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
	from /home/sfunke/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
	from /home/sfunke/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
	from /home/sfunke/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
Processing by ExceptionHandler::ExceptionController#show as HTML
Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)
Error during failsafe response: [401] You are not authorized! Provide a valid X-PAPI-API-KEY HTTP Header to use this resource!
  /home/sfunke/android-privacy-api-servers/papi-backend/papi-backend/app/controllers/application_controller.rb:55:in `check_api_authorization'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:432:in `block in make_lambda'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:164:in `call'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:164:in `block in halting'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `call'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `block in call'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `each'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `call'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `block in instrument'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `instrument'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activerecord-4.2.6/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/abstract_controller/base.rb:137:in `process'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionview-4.2.6/lib/action_view/rendering.rb:30:in `process'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_controller/metal.rb:196:in `dispatch'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_controller/metal.rb:237:in `block in action'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/exception_handler-0.5.1/lib/exception_handler.rb:78:in `call'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/exception_handler-0.5.1/lib/exception_handler.rb:78:in `block (2 levels) in <class:Engine>'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/middleware/show_exceptions.rb:47:in `call'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/middleware/show_exceptions.rb:47:in `render_exception'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/middleware/show_exceptions.rb:35:in `rescue in call'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/railties-4.2.6/lib/rails/rack/logger.rb:38:in `call_app'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `block in call'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:26:in `tagged'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `tagged'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `call'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/activesupport-4.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/actionpack-4.2.6/lib/action_dispatch/middleware/static.rb:120:in `call'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/railties-4.2.6/lib/rails/engine.rb:518:in `call'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/railties-4.2.6/lib/rails/application.rb:165:in `call'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
  /home/sfunke/.rvm/gems/ruby-2.2.3@papi-backend/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
  /home/sfunke/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /home/sfunke/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /home/sfunke/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

Could it be, that exceptions thrown in the main applications ApplicationController or in controllers that inherit from it get not catched from exception_handler?
I tried jumping with my byebug debugger in the exception_handlers controller show action...it does not arrive there out of some reason?

Thanks a lot for your help!

**Comment by richpeck** [comment]
Hi there, thanks for the interesting query.

A question about the Papi API - is this called each time you use `ApplicationController` with a `before_action` or similar? 

Looking at your StackTrace (thanks btw), it seems that EH is catching the error but it's unable to process it because it's being invoked again. If you remove the check and try to manually raise the exception for an action (IE not as a `before_action`), could you tell me if that works?

Sorry for the short reply, it's late and I am quite tired

R

**Comment by defec8edc0de** [comment]
Yes, you are right: `app/controllers/application_controller.rb:55:in check_api_authorization'`
gets invoked with `before_action`!

And this seems indeed to be the problem, because when I uncomment the `before_action :check_api_authorization` in the ApplicationController and invoke `check_api_authorization` (without API key to raise the exception in it) manually in some controller everything works fine!

Any idea how to solve this issue with before_action?

**Comment by richpeck** [comment]
If I remember rightly, you copied the ExceptionHandler controller to your own app? If that's the case, you can subclass EH from `ActionController::Base` (not `ApplicationController`):

https://github.com/richpeck/exception_handler/blob/master/app/controllers/exception_handler/exception_controller.rb#L2

```class  ExceptionController < ActionController::Base```

This will prevent EH from engaging with `ApplicationController`, hence stopping the `before_action` form invoking. 

If you want to keep `ApplicationController` as the superclass, you'll want to use `skip_before_action` in the EH controller:

http://apidock.com/rails/v4.0.2/AbstractController/Callbacks/ClassMethods/skip_before_action

```
#app/controllers/exception_handler/exception_controller.rb
class ExceptionHandler::ExceptionController < ApplicationController
   skip_before_action :check_api_authorization
```
