### ISSUE TITLE
Only Rails FAILSAFE message is being shown

### ISSUE THREAD

**Issue by pcragone** [richpeck/exception_handler#36]
I'm guessing I'm doing something wrong, but the only error message that shows up is:

```
500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.
```

Running `Rails 4.1` and `Ruby 2.3.1`.

The only thing I did to "install" exception_handler is to put it in my Gemfile:

```
gem 'exception_handler', '~> 0.5.0' #-> Gemfile
```

**Comment by richpeck** [comment]
Hi there, many thanks for the comment.

This error is typically raised if a core issue is raised (circumventing `ActionView` etc), do you have the console log I could look at to verify what the problem is?

Many thanks!!

R

**Comment by pcragone** [comment]
I'm having trouble replicating this in a newly-created application, so I'm guessing it's something I put in either an initializer or somewhere else.  In any case, if you can help me troubleshoot, I'd appreciate it.

For the record, this is being run locally, but in production mode.  Here's the log file output:
```
I, [2016-08-31T08:01:42.442845 #19648]  INFO -- : [remo] [5565bc81-8e24-48f6-8d34-cc64c9b79574] Started GET "/asdfasdfasd" for 127.0.0.1 at 2016-08-31 08:01:42 -0400
F, [2016-08-31T08:01:42.448128 #19648] FATAL -- : [remo] [5565bc81-8e24-48f6-8d34-cc64c9b79574] 
ActionController::RoutingError (No route matches [GET] "/asdfasdfasd"):
  actionpack (4.1.10) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  rollbar (2.8.2) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.1.10) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  railties (4.1.10) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.10) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.10) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.10) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.10) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.10) lib/rails/rack/logger.rb:20:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.1.10) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  activesupport (4.1.10) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.1.10) lib/action_dispatch/middleware/static.rb:84:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  skylight (0.10.3) lib/skylight/middleware.rb:61:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  railties (4.1.10) lib/rails/engine.rb:514:in `call'
  railties (4.1.10) lib/rails/application.rb:144:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.5.5) lib/rack/content_length.rb:14:in `call'
  puma (2.11.2) lib/puma/server.rb:507:in `handle_request'
  puma (2.11.2) lib/puma/server.rb:375:in `process_client'
  puma (2.11.2) lib/puma/server.rb:262:in `block in run'
  puma (2.11.2) lib/puma/thread_pool.rb:104:in `block in spawn_thread'


I, [2016-08-31T08:01:42.453402 #19648]  INFO -- : [remo] [5565bc81-8e24-48f6-8d34-cc64c9b79574] [Rollbar] Scheduling payload
I, [2016-08-31T08:01:42.453485 #19648]  INFO -- : [remo] [5565bc81-8e24-48f6-8d34-cc64c9b79574] [Rollbar] Sending payload
W, [2016-08-31T08:01:42.726759 #19648]  WARN -- : [remo] [5565bc81-8e24-48f6-8d34-cc64c9b79574] [Rollbar] Got unexpected status code from Rollbar api: 400
I, [2016-08-31T08:01:42.726871 #19648]  INFO -- : [remo] [5565bc81-8e24-48f6-8d34-cc64c9b79574] [Rollbar] Response: {
  "err": 1,
  "message": "access token required"
}
I, [2016-08-31T08:01:42.726924 #19648]  INFO -- : [remo] [5565bc81-8e24-48f6-8d34-cc64c9b79574] [Rollbar] Details: https://rollbar.com/instance/uuid?uuid=26f2b376-134b-496d-975f-295ecca7144d (only available if report was successful)
I, [2016-08-31T08:01:42.727674 #19648]  INFO -- : [remo] [5565bc81-8e24-48f6-8d34-cc64c9b79574] Processing by ExceptionHandler::ExceptionController#show as HTML
I, [2016-08-31T08:01:42.729022 #19648]  INFO -- : [remo] [5565bc81-8e24-48f6-8d34-cc64c9b79574] Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)
```

And here's the output from the console:
```
=> Booting Puma
=> Rails 4.1.10 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Notice: server is listening on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--binding option)
=> Ctrl-C to shutdown server
Puma 2.11.2 starting...
* Min threads: 0, max threads: 16
* Environment: production
* Listening on tcp://0.0.0.0:3000
Error during failsafe response: uncaught throw :warden
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/warden-1.2.3/lib/warden/proxy.rb:128:in `throw'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/warden-1.2.3/lib/warden/proxy.rb:128:in `authenticate!'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/devise-3.4.1/lib/devise/controllers/helpers.rb:112:in `authenticate_user!'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:429:in `block in make_lambda'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:161:in `block in halting'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:501:in `block in call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:501:in `each'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:501:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:86:in `run_callbacks'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/actionpack-4.1.10/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/actionpack-4.1.10/lib/action_controller/metal/rescue.rb:29:in `process_action'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/actionpack-4.1.10/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/activesupport-4.1.10/lib/active_support/notifications.rb:159:in `block in instrument'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/activesupport-4.1.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/activesupport-4.1.10/lib/active_support/notifications.rb:159:in `instrument'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/actionpack-4.1.10/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/actionpack-4.1.10/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/activerecord-4.1.10/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/actionpack-4.1.10/lib/abstract_controller/base.rb:136:in `process'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/actionview-4.1.10/lib/action_view/rendering.rb:30:in `process'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/actionpack-4.1.10/lib/action_controller/metal.rb:196:in `dispatch'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/actionpack-4.1.10/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/actionpack-4.1.10/lib/action_controller/metal.rb:232:in `block in action'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/exception_handler-0.5.1/lib/exception_handler.rb:78:in `block (2 levels) in <class:Engine>'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/actionpack-4.1.10/lib/action_dispatch/middleware/show_exceptions.rb:46:in `render_exception'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/actionpack-4.1.10/lib/action_dispatch/middleware/show_exceptions.rb:35:in `rescue in call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/actionpack-4.1.10/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/railties-4.1.10/lib/rails/rack/logger.rb:38:in `call_app'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/railties-4.1.10/lib/rails/rack/logger.rb:20:in `block in call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/activesupport-4.1.10/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/activesupport-4.1.10/lib/active_support/tagged_logging.rb:26:in `tagged'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/activesupport-4.1.10/lib/active_support/tagged_logging.rb:68:in `tagged'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/railties-4.1.10/lib/rails/rack/logger.rb:20:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/request_store-1.1.0/lib/request_store/middleware.rb:8:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/actionpack-4.1.10/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/activesupport-4.1.10/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/actionpack-4.1.10/lib/action_dispatch/middleware/static.rb:84:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/skylight-0.10.3/lib/skylight/middleware.rb:61:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/railties-4.1.10/lib/rails/engine.rb:514:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/railties-4.1.10/lib/rails/application.rb:144:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/rack-1.5.5/lib/rack/content_length.rb:14:in `call'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/puma-2.11.2/lib/puma/server.rb:507:in `handle_request'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/puma-2.11.2/lib/puma/server.rb:375:in `process_client'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/puma-2.11.2/lib/puma/server.rb:262:in `block in run'
  /Users/pragone/.rvm/gems/ruby-2.3.1@mygemset/gems/puma-2.11.2/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

**Comment by pcragone** [comment]
Unfortunately, even with an empty `application.haml` file, I'm getting the same error.

**Comment by richpeck** [comment]
Do you have a repo I could look at?

**Comment by pcragone** [comment]
Unfortunately at the moment I do not (problem is happening in a private repo).  I'm trying to replicate it in a fresh project, but having difficulty with it, but unfortunately that information has not helped me pinpoint where in my app I've created the problem.

**Comment by pcragone** [comment]
Alright looks like this is a combination of two issues.

First, as you mentioned, was my `application.haml` file.  More specifically, it was that file attempting to use path helpers and presumably-existing methods from Devise that were not, in fact, available.

Second, the devise method `authenticate_user!`, which is run as a `before_filter` in my `ApplicationController` does something that does not play nicely with this exception handling process.  Presumably, it falls in line with the first problem - calling something that doesn't exist when it assumes it does.

**Comment by richpeck** [comment]
Yes, I've had that issue before. Have you tried `skip_before_action` in the `ExceptionController`?

**Comment by pcragone** [comment]
Ah good idea.  Since I'm currently just using everything out of the box from exception_handler, I added this line to my `ApplicationController`:
```
skip_before_filter :authenticate_user!, if: Proc.new { controller_name.to_s == 'exception'}
```

That seems to have solved the problem for, now at least.

**Comment by pcragone** [comment]
Hi @richpeck -

Seems that the main, actual "issue" here is that when using `exception_handler`, all links on every page have to be reference to `main_app`, which is rather frustrating.  Is there any easy way around that?

**Comment by richpeck** [comment]
It's not every page, it's only the `application` layout because it's used for the 404 error. You can change the layout called in the 404 error with another of your choice:

<img src="https://github.com/richpeck/exception_handler/blob/master/readme/config_defaults.jpg?raw=true"> - I've forgotten if the "layouts" feature works in the config, if not I can push a new version otherwise you'll be able to add an `ExceptionController` with explicit declaration of that layout on there.

**Comment by pcragone** [comment]
Ahhh It seems `exception_handler` assumes the existence of a `root_url` path, which I did not have in my application.

It may be worthwhile to raise that as an error on startup, if possible?  Or use an alternative if it doesn't exist? (Perhaps just '/')

**Comment by dkniffin** [comment]
I also had this issue when migrating an app from an existing setup to Heroku, and it was caused by me forgetting to run `rake db:migrate` 🤦‍♂️

**Comment by richpeck** [comment]
@dkniffin Did the issue resolve after the migration?

**Comment by dkniffin** [comment]
The `rake db:migrate` resolved the issue. I was just posting that comment here for posterity, in case someone else found this result from Google, like I did :)

**Comment by richpeck** [comment]
That's good to hear!!

**Comment by aesyondu** [comment]
> Ah good idea. Since I'm currently just using everything out of the box from exception_handler, I added this line to my `ApplicationController`:
> 
> ```
> skip_before_filter :authenticate_user!, if: Proc.new { controller_name.to_s == 'exception'}
> ```
> 
> That seems to have solved the problem for, now at least.

This solved my issue. I just changed 'exception' to 'exceptions' and it worked. Thanks!
