### ISSUE TITLE
New :exceptions hash not working

### ISSUE THREAD

**Issue by soundnotation** [richpeck/exception_handler#81]
My 404 exception is rendered by our ErrorsController as follows:

```
class ErrorsController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:not_found, :internal_server_error]
  def not_found
    render(:status => 404)
  end

  def internal_server_error
    render(:status => 500)
  end
end
```

The respecting view is located under `app/views/exceptions/show.html.erb`.
With the old hash, things worked out neatly (the view was rendered as expected):

```
    config.exception_handler = {
      dev: false,
      layouts: {
        404 => "not_found"
      }
    }
```

But the following configuration (new hash):

```
    config.exception_handler = {
      dev: false,
      exceptions: {
        404 => { layout: "not_found" },
      }
    }
```

does not render the view anymore. Instead, it just renders a blank page with only this content:

![image](https://user-images.githubusercontent.com/23723634/52133310-5b6b5000-2641-11e9-9244-137b83ac4547.png)

I'm struggling to figure out what's going on.
I even had a look at your custom exceptions section and tried to put a config line like this:
```
      custom_exceptions: {
        'ErrorsController' => :not_found
      },
```
but that does not help.
Here's the response log of the old configuration:
```
I, [2019-02-01T16:01:25.934195 #109180]  INFO -- : [4bd2e316-ef8e-4898-ac66-dd98a146731d] Started GET "/asd" for 217.237.64.186 at 2019-02-01 16:01:25 +0000
F, [2019-02-01T16:01:25.935899 #109180] FATAL -- : [4bd2e316-ef8e-4898-ac66-dd98a146731d]
F, [2019-02-01T16:01:25.936037 #109180] FATAL -- : [4bd2e316-ef8e-4898-ac66-dd98a146731d] ActionController::RoutingError (No route matches [GET] "/asd"):
F, [2019-02-01T16:01:25.936124 #109180] FATAL -- : [4bd2e316-ef8e-4898-ac66-dd98a146731d]
F, [2019-02-01T16:01:25.936196 #109180] FATAL -- : [4bd2e316-ef8e-4898-ac66-dd98a146731d] actionpack (5.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
[4bd2e316-ef8e-4898-ac66-dd98a146731d] actionpack (5.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[4bd2e316-ef8e-4898-ac66-dd98a146731d] railties (5.2.2) lib/rails/rack/logger.rb:38:in `call_app'
[4bd2e316-ef8e-4898-ac66-dd98a146731d] railties (5.2.2) lib/rails/rack/logger.rb:26:in `block in call'
[4bd2e316-ef8e-4898-ac66-dd98a146731d] activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `block in tagged'
[4bd2e316-ef8e-4898-ac66-dd98a146731d] activesupport (5.2.2) lib/active_support/tagged_logging.rb:28:in `tagged'
[4bd2e316-ef8e-4898-ac66-dd98a146731d] activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `tagged'
[4bd2e316-ef8e-4898-ac66-dd98a146731d] railties (5.2.2) lib/rails/rack/logger.rb:26:in `call'
[4bd2e316-ef8e-4898-ac66-dd98a146731d] actionpack (5.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[4bd2e316-ef8e-4898-ac66-dd98a146731d] request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
[4bd2e316-ef8e-4898-ac66-dd98a146731d] actionpack (5.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
[4bd2e316-ef8e-4898-ac66-dd98a146731d] rack (2.0.6) lib/rack/method_override.rb:22:in `call'
[4bd2e316-ef8e-4898-ac66-dd98a146731d] rack (2.0.6) lib/rack/runtime.rb:22:in `call'
[4bd2e316-ef8e-4898-ac66-dd98a146731d] activesupport (5.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[4bd2e316-ef8e-4898-ac66-dd98a146731d] actionpack (5.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
[4bd2e316-ef8e-4898-ac66-dd98a146731d] actionpack (5.2.2) lib/action_dispatch/middleware/static.rb:127:in `call'
[4bd2e316-ef8e-4898-ac66-dd98a146731d] rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
[4bd2e316-ef8e-4898-ac66-dd98a146731d] railties (5.2.2) lib/rails/engine.rb:524:in `call'
[4bd2e316-ef8e-4898-ac66-dd98a146731d] puma (3.12.0) lib/puma/configuration.rb:225:in `call'
[4bd2e316-ef8e-4898-ac66-dd98a146731d] puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
[4bd2e316-ef8e-4898-ac66-dd98a146731d] puma (3.12.0) lib/puma/server.rb:472:in `process_client'
[4bd2e316-ef8e-4898-ac66-dd98a146731d] puma (3.12.0) lib/puma/server.rb:332:in `block in run'
[4bd2e316-ef8e-4898-ac66-dd98a146731d] puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
I, [2019-02-01T16:01:25.937445 #109180]  INFO -- : [4bd2e316-ef8e-4898-ac66-dd98a146731d] Processing by ExceptionHandler::ExceptionsController#show as HTML
D, [2019-02-01T16:01:25.940076 #109180] DEBUG -- : [4bd2e316-ef8e-4898-ac66-dd98a146731d]   User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 2], ["LIMIT", 1]]
D, [2019-02-01T16:01:25.941508 #109180] DEBUG -- : [4bd2e316-ef8e-4898-ac66-dd98a146731d]   Cart Load (0.4ms)  SELECT  "carts".* FROM "carts" WHERE "carts"."status" = $1 AND "carts"."id" = $2 AND "carts"."user_id" = $3 LIMIT $4  [["status", 0], ["id", 385], ["user_id", 2], ["LIMIT", 1]]
D, [2019-02-01T16:01:25.942648 #109180] DEBUG -- : [4bd2e316-ef8e-4898-ac66-dd98a146731d]   Currency Load (0.2ms)  SELECT  "currencies".* FROM "currencies" WHERE "currencies"."id" = $1 LIMIT $2  [["id", 3], ["LIMIT", 1]]
I, [2019-02-01T16:01:25.944454 #109180]  INFO -- : [4bd2e316-ef8e-4898-ac66-dd98a146731d]   Rendering exception_handler/exceptions/show.html.erb within layouts/not_found
I, [2019-02-01T16:01:25.945119 #109180]  INFO -- : [4bd2e316-ef8e-4898-ac66-dd98a146731d]   Rendered exception_handler/exceptions/show.html.erb within layouts/not_found (0.5ms)I, [2019-02-01T16:01:25.946964 #109180]  INFO -- : [4bd2e316-ef8e-4898-ac66-dd98a146731d]   Rendered layouts/_error_page_nav.html.erb (1.0ms)
I, [2019-02-01T16:01:25.947362 #109180]  INFO -- : [4bd2e316-ef8e-4898-ac66-dd98a146731d]   Rendered layouts/_error_logo_section.html.erb (0.2ms)
I, [2019-02-01T16:01:25.949458 #109180]  INFO -- : [4bd2e316-ef8e-4898-ac66-dd98a146731d]   Rendered layouts/_footer.html.erb (1.8ms)
I, [2019-02-01T16:01:25.949752 #109180]  INFO -- : [4bd2e316-ef8e-4898-ac66-dd98a146731d] Completed 404 Not Found in 12ms (Views: 5.6ms | ActiveRecord: 1.1ms)
```

Here's the response log of the new configuration:

```
I, [2019-02-01T15:41:46.784173 #104435]  INFO -- : [73082605-3df4-4013-94d1-e3ae60b8fa88] Started GET "/asd" for 217.237.64.186 at 2019-02-01 15:41:46 +0000
F, [2019-02-01T15:41:46.785309 #104435] FATAL -- : [73082605-3df4-4013-94d1-e3ae60b8fa88]
F, [2019-02-01T15:41:46.785348 #104435] FATAL -- : [73082605-3df4-4013-94d1-e3ae60b8fa88] ActionController::RoutingError (No route matches [GET] "/asd"):
F, [2019-02-01T15:41:46.785369 #104435] FATAL -- : [73082605-3df4-4013-94d1-e3ae60b8fa88]
F, [2019-02-01T15:41:46.785392 #104435] FATAL -- : [73082605-3df4-4013-94d1-e3ae60b8fa88] actionpack (5.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
[73082605-3df4-4013-94d1-e3ae60b8fa88] actionpack (5.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[73082605-3df4-4013-94d1-e3ae60b8fa88] railties (5.2.2) lib/rails/rack/logger.rb:38:in `call_app'
[73082605-3df4-4013-94d1-e3ae60b8fa88] railties (5.2.2) lib/rails/rack/logger.rb:26:in `block in call'
[73082605-3df4-4013-94d1-e3ae60b8fa88] activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `block in tagged'
[73082605-3df4-4013-94d1-e3ae60b8fa88] activesupport (5.2.2) lib/active_support/tagged_logging.rb:28:in `tagged'
[73082605-3df4-4013-94d1-e3ae60b8fa88] activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `tagged'
[73082605-3df4-4013-94d1-e3ae60b8fa88] railties (5.2.2) lib/rails/rack/logger.rb:26:in `call'
[73082605-3df4-4013-94d1-e3ae60b8fa88] actionpack (5.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[73082605-3df4-4013-94d1-e3ae60b8fa88] request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
[73082605-3df4-4013-94d1-e3ae60b8fa88] actionpack (5.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
[73082605-3df4-4013-94d1-e3ae60b8fa88] rack (2.0.6) lib/rack/method_override.rb:22:in `call'
[73082605-3df4-4013-94d1-e3ae60b8fa88] rack (2.0.6) lib/rack/runtime.rb:22:in `call'
[73082605-3df4-4013-94d1-e3ae60b8fa88] activesupport (5.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[73082605-3df4-4013-94d1-e3ae60b8fa88] actionpack (5.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
[73082605-3df4-4013-94d1-e3ae60b8fa88] actionpack (5.2.2) lib/action_dispatch/middleware/static.rb:127:in `call'
[73082605-3df4-4013-94d1-e3ae60b8fa88] rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
[73082605-3df4-4013-94d1-e3ae60b8fa88] railties (5.2.2) lib/rails/engine.rb:524:in `call'
[73082605-3df4-4013-94d1-e3ae60b8fa88] puma (3.12.0) lib/puma/configuration.rb:225:in `call'
[73082605-3df4-4013-94d1-e3ae60b8fa88] puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
[73082605-3df4-4013-94d1-e3ae60b8fa88] puma (3.12.0) lib/puma/server.rb:472:in `process_client'
[73082605-3df4-4013-94d1-e3ae60b8fa88] puma (3.12.0) lib/puma/server.rb:332:in `block in run'
[73082605-3df4-4013-94d1-e3ae60b8fa88] puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
I, [2019-02-01T15:41:46.785860 #104435]  INFO -- : [73082605-3df4-4013-94d1-e3ae60b8fa88] Processing by ExceptionHandler::ExceptionsController#show as HTML
D, [2019-02-01T15:41:46.788246 #104435] DEBUG -- : [73082605-3df4-4013-94d1-e3ae60b8fa88]   User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 2], ["LIMIT", 1]]
D, [2019-02-01T15:41:46.790151 #104435] DEBUG -- : [73082605-3df4-4013-94d1-e3ae60b8fa88]   Cart Load (0.5ms)  SELECT  "carts".* FROM "carts" WHERE "carts"."status" = $1 AND "carts"."id" = $2 AND "carts"."user_id" = $3 LIMIT $4  [["status", 0], ["id", 385], ["user_id", 2], ["LIMIT", 1]]
D, [2019-02-01T15:41:46.791289 #104435] DEBUG -- : [73082605-3df4-4013-94d1-e3ae60b8fa88]   Currency Load (0.3ms)  SELECT  "currencies".* FROM "currencies" WHERE "currencies"."id" = $1 LIMIT $2  [["id", 3], ["LIMIT", 1]]
I, [2019-02-01T15:41:46.794193 #104435]  INFO -- : [73082605-3df4-4013-94d1-e3ae60b8fa88] Completed 500 Internal Server Error in 8ms (ActiveRecord: 1.2ms)
```
---
Maybe this can help: if I set `dev: true` in the hash, I get an error when starting rails:
```
/home/soundnotation/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:584:in `add_route': Invalid route name, already in use: 'not_found'  (ArgumentError)
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here:
http://guides.rubyonrails.org/routing.html#restricting-the-routes-created
```

**Comment by richpeck** [comment]
Hi there!

Do you have a repo I could investigate? The new hash works well (it was implemented to make the system more granular) -- it may be the case that you have some sort of issue causing the hash to not be read properly. The text you're seeing is a result of the "failsafe" 500 error text from Rails --> https://github.com/rails/rails/blob/4-0-stable/actionpack/lib/action_dispatch/middleware/show_exceptions.rb#L18-L22

If you let me know which repo you're using (so I can see the code), I'll be in a much better position to give feedback.

**Comment by soundnotation** [comment]
Hello Rich,

we host our app on a private repo on Bitbucket. Do you have an account there? Thanks

________________________________
Von: Richard Peck <notifications@github.com>
Gesendet: Friday, February 1, 2019 7:09:26 PM
An: richpeck/exception_handler
Cc: info | soundnotation; Author
Betreff: Re: [richpeck/exception_handler] New :exceptions hash not working (#81)


Hi there!

Do you have a repo I could investigate? The new hash works well (it was implemented to make the system more granular) -- it may be the case that you have some sort of issue causing the hash to not be read properly. The text you're seeing is a result of the "failsafe" 500 error text from Rails --> https://github.com/rails/rails/blob/4-0-stable/actionpack/lib/action_dispatch/middleware/show_exceptions.rb#L18-L22

If you let me know which repo you're using (so I can see the code), I'll be in a much better position to give feedback.

**Comment by richpeck** [comment]
Yes rpeck@frontlineutilities.co.uk

**Comment by richpeck** [comment]
Something strange was going on in your app.

You have a LOT of stuff in there. I mean a huge amount - you need to modularize it as much as possible. 

The issue ended up being two-fold:

1. **You included the following line in `config/application.rb`**:
`config.exceptions_app = ->(env) { ExceptionsController.action(:show).call(env) }` -- this was conflicting with ExceptionHandler and needs to be removed.

2. You have included the `controller` for ExceptionHandler in your local application, but didn't update it in line with the new versions of the system. I removed the `app/controllers/exceptions_controller.rb` and `app/controllers/exception_handler/exceptions_controller.rb` files and it started to work (after fixing assets etc).

![image](https://user-images.githubusercontent.com/1104431/52259692-8c86a180-291b-11e9-902d-9a00278675da.png)

![image2](https://user-images.githubusercontent.com/1104431/52259736-aaec9d00-291b-11e9-8977-1abd40e4e320.png)

I would strongly suggest you remove any traces of the `ExceptionHandler` gem's files from your views/controllers/models folders. This way, you'll be using the provided files from the gem, which are the most up to date.

**Comment by soundnotation** [comment]
Thanks @richpeck , yes it's working correctly right now.
I still have the  `dev: true` problem though:
```
/home/soundnotation/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:584:in `add_route': Invalid route name, already in use: 'not_found' (ArgumentError) You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here: http://guides.rubyonrails.org/routing.html#restricting-the-routes-created
```
Do you know why this happens? Do I need to create another issue?

**Comment by richpeck** [comment]
Oh yeah, it's a route you added to your `config/routes.rb` file (forgot to mention). You need to remove it and the path will work
