### ISSUE TITLE
Failsafe response on 5xx errors from recognize_path routes helper method.

### ISSUE THREAD

**Issue by codemilan** [richpeck/exception_handler#90]
I'm getting error as:
```
Error during failsafe response: undefined method `authenticate?' for nil:NilClass
  /Users/babaji/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/devise-4.6.2/lib/devise/rails/routes.rb:479:in `block in constraints_for'
  /Users/babaji/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0.rc1/lib/action_dispatch/routing/mapper.rb:41:in `block in matches?'
  /Users/babaji/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0.rc1/lib/action_dispatch/routing/mapper.rb:39:in `all?'
  /Users/babaji/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0.rc1/lib/action_dispatch/routing/mapper.rb:39:in `matches?'
  /Users/babaji/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0.rc1/lib/action_dispatch/routing/route_set.rb:866:in `block in recognize_path_with_request'
  /Users/babaji/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0.rc1/lib/action_dispatch/journey/router.rb:72:in `block in recognize'
  /Users/babaji/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0.rc1/lib/action_dispatch/journey/router.rb:65:in `each'
  /Users/babaji/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0.rc1/lib/action_dispatch/journey/router.rb:65:in `recognize'
  /Users/babaji/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0.rc1/lib/action_dispatch/routing/route_set.rb:856:in `recognize_path_with_request'
  /Users/babaji/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0.rc1/lib/action_dispatch/routing/route_set.rb:852:in `recognize_path'
  /Users/babaji/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/exception_handler-0.8.0.0/app/views/exception_handler/exceptions/show.html.erb:1:in `___sers_babaji__rbenv_versions_______lib_ruby_gems_______gems_exception_handler_________app_views_exception_handler_exceptions_show_html_erb___3540024730038398337_70161348941340'
```

The issue is caused on reaching "Rails.application.routes.recognize_path("/")" in show.html.erb from the gem.
version: (0.8.0.0)

**Comment by richpeck** [comment]
Good morning, sorry about the lateness of the reply - have been very busy.

Can you give context? I believe there is a [skip_before_filter](https://github.com/richpeck/exception_handler/blob/master/app/controllers/exception_handler/exceptions_controller.rb#L13) on the controller, which should bypass this error?

**Comment by codemilan** [comment]
@richpeck thankyou, 'skip_before_filter' did the trick.

**Comment by richpeck** [comment]
Great to hear :)
